pipeline{
agent any
stages
{
stage("SCM Checkout")
{
steps
{
git 'https://github.com/ArunachalamAlagappan/JavaMavenJenkinsRepo/tree/master/TestMavenApp'
}
}
stage("Code compilation")
{
steps
{
sh 'mvn package'
}
}
}
}
